### ISSUE TITLE
Unserialize-Problem

### ISSUE THREAD

**Issue by chriskonnertz** [OfficialJoe/Contentify-Contribution#1]
Hello,

sorry for my late answer.

About your problem here: https://github.com/OfficialJoe/Contentify-Contribution/blob/master/Demo%20Backend.log

According to this http://stackoverflow.com/questions/16863156/laravel-4-unserialize-error-at-offset-0-of-32-bytes and that http://stackoverflow.com/questions/28248670/laravel-unserialize-error-at-offset-0-of-355-bytes , have you tried to clear the cache?

**Comment by OfficialJoe** [comment]
Thanks I will try later since im really busy
